const { colorList, materialType, countriesList, batteryTypes, unitCountTypeArray } = require("../citizenList");

export const headerOptionValues = {

    'brand-name'                    :  "", 
    'product-name'                  : "",
    'product-description'           : "",
     'key-features'                 : "",
     'search-keywords'              : "",
      'target-gender'               : ["Male", "Female", "Unisex"],
      'age-range-description'       : ["Kid", "Teen", "Adult"],
      'product-color'               : colorList,
      'product-size'                : "",
      'number-of-item'              : "",
      'material'                    :  materialType,
      'style'                       : "",
      'pattern'                     : "",
      'unitcount'                   : "",
      'unit-count-type'             : unitCountTypeArray,
       'item-type-name'             : "",
        'recommended-use'           : "",
        'model-name'                : "",
        'model-number'              : "",
        'manufacturepart-number'    : "",
        'country-of-origin'         : countriesList,
        'manufacturer'              : "",
        'packer-contact-information': "",
        'importer-details'          : "",
        'tax-code'                  : "",
        'tax-rate'                  : "",
        'fullfilment-by'            :  ['Seller'],
        'shipping-provider'         : ['Merchant'],
        'productlength'             : "",
        'product-length-unit'       : ['Centimetres', 'Metres', 'Inches', "Feet","Yards"],
        'product-width'             : "",
        'product-width-unit'        : ['Centimetres', 'Metres', 'Inches', "Feet","Yards"],
        'product-height'            : "",
        'product-height-unit'       : ['Centimetres', 'Metres', 'Inches', "Feet","Yards"],
        'product-weight'            : "",
        'product-weight-unit'       : ['Milligrams', 'Grams', 'Kilograms', "Ounces", "Pounds"],
        'package-length'            : "",
        'package-lengthunit'        : ['Centimetres', 'Metres', 'Inches', "Feet","Yards"],
        'package-width'             : "",
        'package-width-unit'        : ['Centimetres', 'Metres', 'Inches', "Feet","Yards"],
        'package-height'            : "",
        'package-height-unit'       : ['Centimetres', 'Metres', 'Inches', "Feet","Yards"],
    'package-weight'                : "",
        'package-weight-unit'       : ['Milligrams', 'Grams', 'Kilograms', "Ounces", "Pounds"],
        'main_image'                : "",   
        'image_1'                   : "",
        'image_2'                   : "",
        'image_3'                   : "",
        'image_4'                   : "",
        'image_5'                   : "",
        'image_6'                   : "",
        'image_7'                   : "",
        'product-id'                : "",
        'product-id-type'            : ["UPC", "EIN", "GTIN", "ISBN"],
        'sku'                       : "",
        'listing-status'            : ['Active', 'Draft'],
        'msrp'                      : "",
        'consumer-sale-price'       : "",
        'business-sale-price'       : "",
        'stock'                     : "",
        'currency'                  : ["USD"],
        'condition-type'            : ["New"],
        'expire-date'               : "",
        'variant'                   : ['Yes', 'No'],
        'variant-image'             : ['Yes', 'No'],
        'variant_image_1'           : "",
        'variant_image_2'           : "",
        'variant_image_3'           : "",
        'variant_image_4'           : "",
        'variant_image_5'           : "",
        'variant_image_6'           : "",
        'variant_image_7'           : "",
        'contains-liquid-contents'  :  ["Yes", "No"],
        'liquid-volume'             : "",
        'liquid-volume-unit'        : ["Millilitres", "Gram", "OZ", "KG"],
        'is-the-item-heat-sensitive' : ["Yes", "No"],
        'heat-sensitive-instructions' : "",
        'is-the-liquid-product-double-sealed' : ["Yes", "No"],
        'product-double-sealed-instructions' : "",
        'dangerous-goods-regulations' : ["GHS", "Storage", "Transportation", "Waste", "Other", "Not Applicable", "Unknown"],
        'safety-warning'                : "",
        'has-written-warranty'          : "",
        'product-is-or-contains-an-electronic-component' : "",
        'product-is-or-contains-this-battery-type' : ["Yes", "No"],
        'are-batteries-included'        : ["Yes", "No"],
        'battery-cell-composition'      : batteryTypes,
        'quantity-base-discount-type'   : ["percentage", "fixed"],
        'threshold-level-1-unit'        : "",
        'threshold-level-1-discount'    : "",
        'threshold-level-2-unit'        : "",
        'threshold-level-2-discount'    : "",
        'threshold-level-3-unit'        : "",
        'threshold-level-3-discount'    : "",
        'threshold-level-4-unit'        : "",
        'threshold-level-4-discount'    : "",
        'threshold-level-5-unit'        : "",
        'threshold-level-5-discount'    : ""
 };