
export const exportProductField = [ 
          "Dyanamic Product Id",
          "Category",
          "Sub Category",
          "Child Category",
          "Brand Name",
          "Product Name",
          "Product Description",
          "Key Features 1",
          "Key Features 2",
          "Key Features 3",
          "Key Features 4",
          "Key Features 5",
          "Search Keywords",
          "Target Gender",
          "Age Range Description",
          "Product Color",
          "Product Size",
          "Number Of Item",
          "Material",
          "Product Style",
          "Pattern",
          "Unit Count",
          "Unit Count Type",
          "Item Type Name",
          "Recommended Use",
          "Model Name",
          "Model Number",
          "Manufacture Part Number",
          "Country Of Origin",
          "Manufacturer",
          "Packer Contact Information",
          "Importer Details",
          "Tax Code",
          "Tax Rate",
          "Fullfilment By",
          "Shipping Provider",
          "Product Length",
          "Product Length Unit", 
          "Product Width",
          "Product Width Unit",
    
          "Product Height",
          "Product Height Unit",
    
          "Product Weight",
          "Product Weight Unit",
    
          "Package Length",
          "Package Length Unit",
    
          "Package Width",
          "Package Width Unit",
    
          "Package Height",
          "Package Height Unit",
    
          "Package Weight",
          "Package Weight Unit",
          "Handling Time",
    
          "Main Image",
          "Image_1",
          "Image_2",
          "Image_3",
          "Image_4",
          "Image_5",
          "Image_6",
          "Image_7",
    
     
];


export const productFieldDataTypes = [ 
         "This is system genrated id",   // "Dyanamic Product Id",
         "Select value from dropdown",   // "Category",
         "Select value from dropdown",   // "Sub Category",
         "Select value from dropdown",   // "Child Category",
         "Text",                         // "Brand Name",
         "Text",                         // "Product Name",
         "Text",                         // "Product Description",
         "Text",                         // "Key Features 1",
         "Text",                         // "Key Features 2",
         "Text",                         // "Key Features 3",
         "Text",                         // "Key Features 4",
         "Text",                         // "Key Features 5",
         "Text",                         // "Search Keywords",
         "Select value from dropdown",   // "Target Gender",
         "Select value from dropdown",   // "Age Range Description",
         "Select value from dropdown",   // "Product Color",
         "Text",                         // "Product Size",
         "Number",                       // "Number Of Item",
         "Text",                         // "Material",
         "Text",                         // "Product Style",
         "Text",                         // "Pattern",
         "Number",                       // "Unit Count",
         "Select value from dropdown",   // "Unit Count Type",
         "Text",                         // "Item Type Name",
         "Text",                         // "Recommended Use",
         "Text/Numerical",               // "Model Name",
         "Text/Numerical",               // "Model Number",
         "Text/Numerical",               // "Manufacture Part Number",
         "Select value from dropdown",   // "Country Of Origin",
         "Text",                         // "Manufacturer",
         "Text",                         // "Packer Contact Information",
         "Text",                         // "Importer Details",
         "Numerical",                    // "Tax Code",
         "Numerical",                    // "Tax Rate",
         "Select value from dropdown",   // "Fullfilment By",
         "Select value from dropdown",   // "Shipping Provider",
         "Numerical",                    // "Product Length",
         "Select value from dropdown",   // "Product Length Unit", 
         "Numerical",                    // "Product Width",
         "Select value from dropdown",   // "Product Width Unit",
    
         "Numerical",                    // "Product Height",
         "Select value from dropdown",   // "Product Height Unit",
    
         "Numerical",                    // "Product Weight",
         "Select value from dropdown",   // "Product Weight Unit",
    
         "Numerical",                    // "Package Length",
         "Select value from dropdown",   // "Package LengthUnit",
    
         "Numerical",                    // "Package Width",
         "Select value from dropdown",   // "Package Width Unit",
    
         "Numerical",                    // "Package Height",
         "Select value from dropdown",   // "Package Height Unit",
    
         "Numerical",                    // "Package Weight",
         "Select value from dropdown",   // "Package Weight Unit",
         "Numerical",                    //"Handling Time",
    
         "image url",                   // "Main Image",
         "image url",                   // "Image_1",
         "image url",                   // "Image_2",
         "image url",                   // "Image_3",
         "image url",                   // "Image_4",
         "image url",                   // "Image_5",
         "image url",                   // "Image_6",
         "image url",                   // "Image_7",
    
     
];




export const fillExampleField = [ 
         "Optional",                   // "Dyanamic Product Id",
         "Mandatory*",                   // "Category",
         "Mandatory*",                   // "Sub Category",
         "Mandatory*",                   // "Child Category",
         "Mandatory*",                   // "Brand Name",
         "Mandatory*",                   // "Product Name",
         "Mandatory*",                   // "Product Description",
         "Mandatory*",                   // "Key Features 1",
         "Optional",                         // "Key Features 2",
         "Optional",                         // "Key Features 3",
         "Optional",                         // "Key Features 4",
         "Optional",                         // "Key Features 5",
         "Mandatory*",                   // "Search Keywords",
         "Mandatory*",                   // "Target Gender",
         "Optional",                     // "Age Range Description",
         "Optional",                     // "Product Color",
         "Optional",                         // "Product Size",
         "Mandatory*",                       // "Number Of Item",
         "Optional",                         // "Material",
         "Optional",                         // "Product Style",
         "Optional",                         // "Pattern",
         "Mandatory*",                       // "Unit Count",
         "Mandatory*",                       // "Unit Count Type",
         "Mandatory*",                       // "Item Type Name",
         "Optional",                         // "Recommended Use",

         "Mandatory*",                        // "Model Name",
         "Mandatory*",                        // "Model Number",
         "Mandatory*",                        // "Manufacture Part Number",
         "Mandatory*",                        // "Country Of Origin",
         "Mandatory*",                        // "Manufacturer",

         "Optional",                          // "Packer Contact Information",
         "Optional",                          // "Importer Details",
         "Optional",                          // "Tax Code",
         "Optional",                          // "Tax Rate",
         "Mandatory*",                        // "Fullfilment By",
         "Mandatory*",                        // "Shipping Provider",
         "Optional",                          // "Product Length",
         "Optional",                          // "Product Length Unit", 

         "Optional",                          // "Product Width",
         "Optional",                          // "Product Width Unit",
    
         "Optional",                          // "Product Height",
         "Optional",                          // "Product Height Unit",
    
         "Optional",                          // "Product Weight",
         "Optional",                          // "Product Weight Unit",
    
         "Optional",                          // "Package Length",
         "Optional",                          // "Package LengthUnit",
    
         "Optional",                          // "Package Width",
         "Optional",                          // "Package Width Unit",
    
         "Optional",                          // "Package Height",
         "Optional",                          // "Package Height Unit",
    
         "Optional",                          // "Package Weight",
         "Optional",                          // "Package Weight Unit",
         "Mandatory*",                       //"Handling Time",
    
         "Mandatory*",                         // "Main Image",
         "Mandatory*",                         // "Image_1",
         "Optional",                           // "Image_2",
         "Optional",                           // "Image_3",
         "Optional",                           // "Image_4",
         "Optional",                           // "Image_5",
         "Optional",                           // "Image_6",
         "Optional",                           // "Image_7",
     
];




export const detailsInField = [ 
          "The computer should automatically generate a unique ID, and the seller should not be able to edit it.", //Dyanamic Product Id
          "Category",
          "SubCategory",
          "ChildCategory",
          "Brand refers to a type of product manufactured by a company under a particular name.",
          "Title refers to the product title that will appear on the product page. Highlight the brand name and product features that will attract buyers.",
          "Please write few lines describing your product along with a list of products that are compatible with this product. Description is limited to 10000 characters (including spaces). It should not include any hyperlinks, additional offers, or promotion text.",
          "Key Features refers to the defining features of a product that can be highlighted on the website.",
          "Key Features refers to the defining features of a product that can be highlighted on the website.",
          "Key Features refers to the defining features of a product that can be highlighted on the website.",
          "Key Features refers to the defining features of a product that can be highlighted on the website.",
          "Key Features refers to the defining features of a product that can be highlighted on the website.",
          "Search Keywords refers to the words which the customer might use to find a product. These keywords are tagged to the product and when the buyer searches with the appropriate search word(s), the nearest appropriate product is retrieved and displayed on Sellora website. The search output is also based on multiple other factors such as Product Quality, Pricing, etc. Please enter a maximum of 5 keywords for this purpose.",
          "Target Gender",
          "Age Range Description",
          `Color refers to the shade of the product as specified by the brand on the label or sales package. The value 'Multicolor' should be used if the product features a mix of three or more prominent colors. Possible values include 'Red,' 'Black,' etc `,
          `Size refers to the size of the product as mentioned by the brand.`,
          "Number Of Item",
          "Material",
          `Style Code is an alphanumeric code which is given to a product and can be found on the tag or packaging. Style Code remains the same for all Size variants and changes for all Color variants. For example, a red colored product that comes in three different sizes will have the same Style Code.`,
          `Pattern refers to a repeated decorative sketch that is printed or engraved on a product.`,
          "UnitCount",
          "UnitCount Type",
          "Item Type Name",
          "Recommended Use",
          "Model Name",
          "Model Number",
          "ManufacturePart Number",
          "Country of origin or manufacturing or country of assembly in case of imported products",
          "Name and address of the manufacturer",
          "Where manufacturer is not the packer,name and address of packer",
          "Name and address of the importer if the product is being imported",
          "Sellora tax code which decides the goods and services tax for the listing",
          "Tax Rate",
          "Fullfilment of FA listings will be managed by Seller",
          "Information on who will ship the item to the customer",
          "Product Length",
          "Product Length Unit", 
          "Width Of Product",
          "Product Width Unit",
    
          "Height Of Product",
          "Product Height Unit",
    
          "Weight Of Product",
          "Product Weight Unit",
    
          "Length Of Package",
          "Package Length Unit",
    
          "Width Of Package",
          "Package Width Unit",
    
          "Height Of Package",
          "Package Height Unit",
    
          "Weight Of Package",
          "Package Weight Unit",
          "Enter Handling Time (in Days)",
    
          `Image Details - Front View - A full front view of a t shirt is a photo of the shirt from the front, with the model standing straight. It shows the fit, design details, and style. | Minimum Resolution - 1600x1600 | Please see the Image Guidelines sheet for more details.`,
          `Image Details - Front View - A full front view of a t shirt is a photo of the shirt from the front, with the model standing straight. It shows the fit, design details, and style. | Minimum Resolution - 1600x1600 | Please see the Image Guidelines sheet for more details.`,
          `Image Details - Front View - A full front view of a t shirt is a photo of the shirt from the front, with the model standing straight. It shows the fit, design details, and style. | Minimum Resolution - 1600x1600 | Please see the Image Guidelines sheet for more details.`,
          `Image Details - Front View - A full front view of a t shirt is a photo of the shirt from the front, with the model standing straight. It shows the fit, design details, and style. | Minimum Resolution - 1600x1600 | Please see the Image Guidelines sheet for more details.`,
          `Image Details - Front View - A full front view of a t shirt is a photo of the shirt from the front, with the model standing straight. It shows the fit, design details, and style. | Minimum Resolution - 1600x1600 | Please see the Image Guidelines sheet for more details.`,
          `Image Details - Front View - A full front view of a t shirt is a photo of the shirt from the front, with the model standing straight. It shows the fit, design details, and style. | Minimum Resolution - 1600x1600 | Please see the Image Guidelines sheet for more details.`,
          `Image Details - Front View - A full front view of a t shirt is a photo of the shirt from the front, with the model standing straight. It shows the fit, design details, and style. | Minimum Resolution - 1600x1600 | Please see the Image Guidelines sheet for more details.`,
          `Image Details - Front View - A full front view of a t shirt is a photo of the shirt from the front, with the model standing straight. It shows the fit, design details, and style. | Minimum Resolution - 1600x1600 | Please see the Image Guidelines sheet for more details.`,
          
     
];
